name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3
        
      - name: Run tests
        run: make test
